// Generated by Selenium IDE

import Core.LoginTrabajopolis;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class TrabajopolisLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void login_trabajopolis() {
//    LoginTrabajopolis loginTrabajopolis = new LoginTrabajopolis();
//    loginTrabajopolis.test_login();
//    String expected = "5";
//    assertEquals(expected, "5");
  }
  @Test
  public void trabajopolisLogin() {
    driver.get("https://www.trabajopolis.bo/");
    driver.manage().window().setSize(new Dimension(1696, 1026));
    driver.findElement(By.linkText("Ingresar")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("at11.fundacion.jala@gmail.com");
    driver.findElement(By.name("password")).sendKeys("at11.2020");
    driver.findElement(By.cssSelector(".button")).click();
  }
}
