// Generated by Selenium IDE

import Core.WebDriverManager;
import Trabajopolis.BuscarEmpleosPage;
import Trabajopolis.HomePage;
import Trabajopolis.LoginPage;

import Trabajopolis.MyAccountPage;
import Trabajopolis.MyListingsPage;
import Trabajopolis.PersonalInformationPage;
import Trabajopolis.ResumeExperiencePage;
import Trabajopolis.SearchResultJobPage;
import org.junit.After;
import org.junit.Test;

import static org.junit.Assert.*;

public class TrabajopolisLoginTest {

  @After
  public void afterTest(){
    WebDriverManager.getInstance().quitWebDriver();
  }

  @Test
  public void login_trabajopolis() {
    LoginPage loginPage = new LoginPage();
    loginPage.test_login();
    MyAccountPage myAccountPage = new MyAccountPage();
    String expected = myAccountPage.getMiCuentaCantidato();
    String actual = "Mi Perfil";
    assertEquals(expected,actual);
  }

  @Test
  public void search_trabajopolis() {
    LoginPage loginPage = new LoginPage();
    loginPage.test_login();
    MyAccountPage myAccountPage = new MyAccountPage();
    myAccountPage.clickBuscarEmpleos();
    BuscarEmpleosPage buscarEmpleosPage = new BuscarEmpleosPage();
    buscarEmpleosPage.selectCategory("Informática");
    buscarEmpleosPage.selectPostedWithin("30");
    buscarEmpleosPage.clickSearchJob();
    SearchResultJobPage searchResultJobPage = new SearchResultJobPage();
    String actual = searchResultJobPage.getResultTitle();
    String expected = "Resultados de Búsqueda de Empleos";
    assertEquals(actual,expected);
  }

  @Test
  public void search_ThroughtHomePage(){
    LoginPage loginPage = new LoginPage();
    loginPage.test_login();
    MyAccountPage myAccountPage = new MyAccountPage();
    myAccountPage.clickInicio();
    HomePage homePage = new HomePage();
    homePage.setCategory("Internet");
    homePage.setCityListBox("Cochabamba");
    homePage.setEmployementTypeListBox("Full time");
    homePage.setPostedWithinListBox("30");
    homePage.clickSearch();
    SearchResultJobPage searchResultJobPage = new SearchResultJobPage();
    String actual = searchResultJobPage.getResultTitle();
    String expected = "Resultados de Búsqueda de Empleos";
    assertEquals(actual,expected);

  }

  @Test
  public void create_Curriculum(){
    LoginPage loginPage = new LoginPage();
    loginPage.test_login();
    MyAccountPage myAccountPage = new MyAccountPage();
    myAccountPage.clickMisCurriculos();
    MyListingsPage myListingsPage = new MyListingsPage();
    myListingsPage.clickAddCV();
    PersonalInformationPage personalInformationPage = new PersonalInformationPage();
    personalInformationPage.selectIdType("Pasaporte");
    personalInformationPage.setAddressField("c/ laredo");
    personalInformationPage.selectMaritalStatus("Soltero(a)");
    personalInformationPage.clickNextButton();
    ResumeExperiencePage resumeExperiencePage = new ResumeExperiencePage();
    resumeExperiencePage.setCompanyCharge("ingeniero");
    resumeExperiencePage.setCompanyName("entel");
    resumeExperiencePage.selectIndustry("Ingeniería");
    resumeExperiencePage.setCountryExperience("Bolivia");
    resumeExperiencePage.setCityExperience("cochabamba");
    resumeExperiencePage.setStartDate("2/3/2015");
    resumeExperiencePage.setEndDate("2/3/2016");

  }
}
