// Generated by Selenium IDE

import Trabajopolis.LoginPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class TrabajopolisLoginTest {


  @Test
  public void login_trabajopolis() {
    LoginPage loginPage = new LoginPage();
    loginPage.test_login();

  }
}
